### ISSUE TITLE
New Version for Windows references() Fix?

### ISSUE THREAD

**Issue by jyounce** [Josiah/gulp-cachebust#14]
Hi Josiah,

First off your package rocks! When are you going to cut a new version that contains the Windows references() fix? It is much needed. I currently have my gulp-cachebust dep set to a tarball for your commit at cbf1ca62e0d90dfbcc1f08f34e1321191d69e423.

Thanks!

Judd

**Comment by jyounce** [comment]
I see that you upped the version to v0.0.6 that includes this fix. Can you please publish it to npm.

Thanks,

Judd

**Comment by Josiah** [comment]
Published
